# Generated by Django 6.0.5 on 2026-05-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('sales', 'Sales Report'), ('products', 'Product Report'), ('customers', 'Customer Report')], max_length=20)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generated_date'],
            },
        ),
    ]
